sonar.projectKey=food-delivery-frontend
sonar.projectName=Food Delivery Frontend

sonar.sources=src
sonar.tests=src/test
sonar.test.inclusions=src/test/**/*.test.jsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
