sonar.projectKey=food-delivery-auth-service
sonar.projectName=food-delivery-auth-service
sonar.sources=src
sonar.exclusions=src/tests/**
sonar.tests=src/tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
