server {
    listen 80;
    server_name _;

    location ^~ /api/auth {
        rewrite ^/api/auth/?(.*)$ /auth/$1 break;
        proxy_pass http://auth-service:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ^~ /api/restaurants {
        rewrite ^/api/restaurants/?(.*)$ /restaurants/$1 break;
        proxy_pass http://restaurant-service:3002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ^~ /api/orders {
        rewrite ^/api/orders/?(.*)$ /orders/$1 break;
        proxy_pass http://order-service:3003;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ^~ /api/delivery {
        rewrite ^/api/delivery/?(.*)$ /delivery/$1 break;
        proxy_pass http://delivery-service:3004;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        proxy_pass http://frontend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
