name: Order Service CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "order-service/**"

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/food-delivery-order:latest ./order-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/food-delivery-order:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster food-delivery-cluster1 \
            --service food-delivery-order \
            --force-new-deployment \
            --region ${{ secrets.AWS_REGION }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        with:
          projectBaseDir: order-service
          args: -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
