name: Restaurant Service CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "restaurant-service/**"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t ${{ secrets.ECR_REGISTRY }}/food-delivery-restaurant:latest ./restaurant-service

      - name: Push to ECR
        run: docker push ${{ secrets.ECR_REGISTRY }}/food-delivery-restaurant:latest

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster food-delivery-cluster1 \
            --service food-delivery-restaurant \
            --force-new-deployment \
            --region ${{ secrets.AWS_REGION }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        with:
          projectBaseDir: restaurant-service
          args: -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
